### ISSUE TITLE
'cabal install AD' fails when installing semigroupoids

### ISSUE THREAD

**Issue by victorpoughon** [ekmett/ad#44]
When running 'cabal install AD' on ubuntu 14.04.2 with cabal 1.16.0.2:

    src/Data/Semigroup/Foldable/Class.hs:103:10:
        No instance for (Bifoldable (Tagged *))
        arising from the superclasses of an instance declaration
        Possible fix:
        add an instance declaration for (Bifoldable (Tagged *))
        In the instance declaration for `Bifoldable1 (Tagged *)'
    Failed to install semigroupoids-5.0.0.2
    cabal: Error: some packages failed to install:
    ad-4.2.2 depends on semigroupoids-5.0.0.2 which failed to install.
    free-4.12.1 depends on semigroupoids-5.0.0.2 which failed to install.
    semigroupoids-5.0.0.2 failed during the building phase. The exception was:
    ExitFailure 1

**Comment by glguy** [comment]
ad builds against semigroupoids-5.0.0.2 using all the current versions of packages. Could you provide a list of all the versions of packages you're building against via `ghc-pkg list` ?

**Comment by victorpoughon** [comment]
Sure. Could that mean one of those is out of date?

    /var/lib/ghc/package.conf.d:
        Cabal-1.16.0
        array-0.4.0.1
        base-4.6.0.1
        bin-package-db-0.0.0.0
        binary-0.5.1.1
        bytestring-0.10.0.2
        containers-0.5.0.0
        deepseq-1.3.0.1
        directory-1.2.0.1
        filepath-1.3.0.1
        (ghc-7.6.3)
        ghc-prim-0.3.0.0
        (haskell2010-1.1.1.0)
        (haskell98-2.0.0.2)
        hoopl-3.9.0.0
        hpc-0.6.0.0
        integer-gmp-0.5.0.0
        old-locale-1.0.0.5
        old-time-1.1.0.1
        pretty-1.1.1.0
        process-1.1.0.2
        rts-1.0
        template-haskell-2.8.0.0
        time-1.4.0.1
        unix-2.6.0.1

    /home/victor/.ghc/x86_64-linux-7.6.3/package.conf.d:
        StateVar-1.1.0.0
        base-orphans-0.3.2
        bifunctors-5
        comonad-4.2.6
        contravariant-1.3.1.1
        data-reify-0.6
        distributive-0.4.4
        erf-2.0.0.0
        exceptions-0.8.0.2
        hashable-1.2.3.2
        mtl-2.2.1
        nats-0.1.2
        prelude-extras-0.4
        profunctors-5.1.1
        reflection-1.5.2.1
        semigroups-0.16.2.2
        stm-2.4.4
        tagged-0.7.1
        tagged-0.8.0.1
        text-1.2.1.1
        transformers-0.4.3.0
        transformers-compat-0.4.0.4
        unordered-containers-0.2.5.1
        void-0.7

**Comment by glguy** [comment]
My guess is that you've got `bifunctors` compiled against a different version of the `tagged` package than you're compiling `ad` with.

**Comment by ekmett** [comment]
Closing this. We've rejiggered a bunch of stuff around `bifunctors` and `tagged` since this. If someone else gets this issue, please feel free to re-open it.
