### ISSUE TITLE
Double specific implementation of Newton?

### ISSUE THREAD

**Issue by ocharles** [ekmett/ad#46]
When using `Newton.findZero` I'm getting results in about 100ns. If I take the source code and change out `diff'` for `Forward.Double.diff'` I get results in 6ns - a substantial difference. Is there any thought about either having a `.Double` module of this, or maybe a parameterized version that takes `diff'` as an argument?

**Comment by barak** [comment]
To get that kind of speed without such manual specialization you will need to sacrifice a goat under a full moon at midnight and sprinkle its blood on the compiler.

**Comment by ocharles** [comment]
The speed is right there, it just needs a version of `Newton` that uses `ForwardDouble` instead of `Forward`, that's all I'm suggesting.

**Comment by ekmett** [comment]
Assuming that tests clean with travis, I'll ship it.
