### ISSUE TITLE
GHC 8 compatible release needed

### ISSUE THREAD

**Issue by alexanderkjeldaas** [ekmett/ad#58]
ad is no longer in stackage nightly.  That probably means a lot of other packages are blocked as well.

**Comment by mstksg** [comment]
I think the main issue is its dependencies, like https://github.com/ku-fpg/data-reify/issues/6

**Comment by glguy** [comment]
Whether or not a package is on stackage is a concern for the stackage issue tracker, but as far as getting this package uploaded to hackage in a form compatible with GHC 8 I'll upload it as soon as I hear back from @ekmett

**Comment by ocramz** [comment]
One of the infeasible constraints is `transformers > 0.3 && < 0.5`, whereas GHC 8.0.1 Stackage nightly imposes `transformers == 0.5.2.0`

**Comment by ekmett** [comment]
@glguy I have no objection to pushing out a GHC 8 compatible release.

**Comment by glguy** [comment]
[ad-4.3.2.1](http://hackage.haskell.org/package/ad-4.3.2.1) is on hackage now.
