### ISSUE TITLE
Two associated pattern synonyms (KnownConstant / KnownZero) for Mode 

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/ad#65]
Worth noting, it seems like we can replace `isKnownConstant` / `auto` and `isKnownZero` / `zero` with pattern synonyms once we get [associated pattern synonyms](https://ghc.haskell.org/trac/ghc/ticket/8583) (and we can also default `type Scalar t = t`)

```haskell
class (Num t, Num (Scalar t)) => Mode t where
  type Scalar t
  type Scalar t = t

  pattern KnownConstant :: Scalar s -> s
  pattern KnownZero     :: s
  pattern KnownZero     = KnownConstant 0

  (*^) :: Scalar t -> t -> t
  a *^ b = KnownConstant a * b

  (^*) :: t -> Scalar t -> t
  a ^* b = a * KnownConstant b

  (^/) :: Fractional (Scalar t) => t -> Scalar t -> t
  a ^/ b = a ^* recip b
```

And the old 

```haskell
auto :: Mode s => Scalar s -> s
auto = KnownConstant

zero :: Mode s => s
zero = auto' 0

isKnownConstant :: Mode s => s -> Bool
isKnownConstant KnownConstant{} = True
isKnownConstant _               = False

isKnownZero :: Mode s => s -> Bool
isKnownZero KnownZero = True
isKnownZero _         = False
```

while also giving us

```haskell
getKnownConstant :: Mode s => s -> Maybe (Scalar s)
getKnownConstant (KnownConstant n) = Just n
getKnownConstant _                 = Nothing
```

These could be defined in terms of `Prism`s but that rules out [deriving](https://ghc.haskell.org/trac/ghc/wiki/Roles2).

**Comment by ekmett** [comment]
Implemented the pattern synonyms directly in terms of combinators. Dropped support for older GHCs. When we get associated pattern synonyms I'll incorporate them.
