### ISSUE TITLE
Using AD with exceptions

### ISSUE THREAD

**Issue by mbernat** [ekmett/ad#69]
I tried using AD with a function that has a `Typeable` constraint and ran into `Could not deduce (Typeable s) [..] from: Reifies s Tape [..]`.

This seems very similar to the problem described in https://github.com/ekmett/reflection/issues/14.
Am I correct in assuming that this comes from the usage of `reifyTape` in the AD internals and could be fixed by using something closer to the `reifyTypeable` like in the other issue?

**Comment by ekmett** [comment]
Using `reifyTypeable` internally would resolve this issue, yes.
